network:
    version: 2
    renderer: NetworkManager
    ethernets:
        enp1s0:
            dhcp4: yes

        enp2s0:
            dhcp4: yes

        enp3s0:
            dhcp4: no
            addresses: [192.168.10.10/24]

        enp4s0:
            dhcp4: no
            addresses: [192.168.20.10/24]
