network:
    version: 2
    renderer: NetworkManager
    ethernets:
        enp1s0:
            dhcp4: yes

        enp2s0:
            dhcp4: yes

        enp3s0:
            dhcp4: no
            addresses: [192.168.10.10/24]

        enp4s0:
            dhcp4: no
            addresses: [192.168.20.10/24]
    vlans:
        vlan10:
            id: 110 #id also same as client VLAN
            link: enp3s0 #Link of physical LAN interface
            dhcp4: no 
            addresses: [192.168.68.11/24] #Address (network) must be in same as client VLAN
            routes: #gateway config
                 - to: default
                   via: 192.168.100.10 #gateway
           
 
