# Refer https://netcontechnologies.sharepoint.com/:x:/s/Symbian/EfM5dcKJ3KNCr6UfDE10MT0Bt5yjKUrvdH2Pxki-KQtBIw?e=dpL3X2

# ------------ SERVICE CODE ---------------
UNREGISTERED_SERVICE_CODE = 99
TRAFFIC_STEERING_MANAGER = 10
QOS_MANAGER = 11
NETWORK_INTERFACE_MANAGER = 12
DHCP_MANAGER = 13
SPLIT_DNS_MANAGER = 14
VPN_MANAGER = 15
DELETE_DEVICE_MANAGER = 16
SYSTEM_UPGRADE = 17
# ------------ EVENT CODE ---------------
UNREGISTERED_EVENT_CODE = 99

# TrafficSteeringManager
IPTABLES_CONFIGURATION_UPDATE_EVENT = 10

# QoSManager
QOS_CONFIGURATION_UPDATE_EVENT = 10

# NetworkInterfaceManager
SHARE_NETWORK_INTERFACE_INFO_EVENT = 10
NETWORK_INTERFACE_CONFIGURATION_UPDATE_EVENT = 11

# DHCPManager
DHCP_SERVER_CONFIGURATION_UPDATE_EVENT = 10

#SplitDNSManager
SPLIT_DNS_CONFIGURATION_UPDATE_EVENT = 10

#OpenVPNServiceManager
UPDATE_OPENVPN_AND_FRR_CONFIGURATION_EVENT = 10
STOP_OPENVPN_AND_FRR_SERVICE_EVENT = 11

# DeleteDeviceManager
DEVICE_DELETE_EVENT = 10

# ------------ STATUS CODE ---------------

#TrafficSteeringManager and QoSManager
SUCCESSFULLY_APPLIED_CONFIGURATION_DATA = 10
RECEIVED_CONFIGURATION_UPDATE_NOTIFICATION = 11
DOWNLOADED_CONFIGURATION_FILE = 12 
DATA_FETCH_FAILED = 20
EMPTY_CONFIGURATION_DATA = 21
CONFIGURATION_DATA_IN_IMPROPER_FORMAT = 22
CONFIGURATION_FILE_CHECKSUM_MISMATCH = 23
FAILED_TO_APPLY_CONFIGURATION_DATA = 24

# NetworkInterfaceManager
SUCCESSFULLY_SHARED_INTERFACE_INFORMATION = 10
RECEIVED_NOTIFICATION_TO_SHARE_INTERFACE_INFORMATION = 11
UNABLE_TO_GET_INTERFACE_INFORMATION_FROM_SYSTEM = 20
FAILED_TO_SHARE_INTERFACE_INFORMATION = 21

# DeleteDeviceManger
SUCCESSFULLY_DELETED_DEVICE = 10
RECEIVED_DELETE_DEVICE_MESSAGE = 11
FAILED_TO_RESET_USER_CONFIG = 20
FAILED_TO_RESET_NETWORK_INTERFACE_CONFIG = 21
FAILED_TO_RESET_SYSTEM_PROVISIONING_CONFIG = 22
FAILED_TO_RESET_DNSMASQ_CONFIG = 23
FAILED_TO_RESET_OPENVPN_AND_ROUTING_CONFIG = 24

# SystemUpgrade
SYSTEM_UPGRADED_SUCCESSFULLY = 10
SYSTEM_UPDATED_PACKAGE_LIST_UPDATED_SUCCESSFULLY = 11
RECEIVED_SYSTEM_UPGRADED_MESSAGE = 12
SYSTEM_UPGRADE_PACKAGE_INSTALLED_SUCCESSFULLY = 13
ROLLING_BACK_CHIEFNET_APPLICATION = 14
SYSTEM_UPDATED_PACKAGE_LIST_UPDATE_FAILED= 20
FAILED_TO_UPGRADE_PYTHON_DEPENDENT_MODULES= 21
FAILED_TO_INSTALL_DEPENDENT_SYSTEM_UTILITY = 22
FAILED_TO_GET_CPE_VERSION = 23
FAILED_TO_STOP_CHIEFNET_SERVICE = 24
FAILED_TO_START_CHIEFNET_SERVICE = 25
FAILED_TO_INSTALL_SYSTEM_UPGRADE_PACKAGE = 26
FAILED_TO_INSTALL_CHIEFNET_ROLLBACK_VERSION = 27
CHIEFNET_ROLLBACK_VERSION_NOT_FOUND = 28